"""
Flask application for AI text detection.

Provides a web interface and API endpoints for analyzing text to determine
if it was likely generated by AI or written by a human based on perplexity.
"""
import os
import logging
from typing import Union, Tuple, Optional
from flask import Flask, request, jsonify, render_template
from flask.wrappers import Response
from detect_ai import analyze_text

app = Flask(__name__)
logging.basicConfig(level=logging.DEBUG, format='%(asctime)s - %(levelname)s - %(message)s')
app.config.setdefault('PERPLEXITY_THRESHOLD', 50)

def _extract_and_validate_text(req: request) -> Optional[str]:
    """
    Extracts text from the request (form or JSON) and validates it.

    Args:
        req: The Flask request object.

    Returns:
        The extracted text if valid, otherwise None.
    """
    text = None
    if req.method == 'POST':
        if req.form: # Used by home route
            text = req.form.get('text', '')
        elif req.is_json: # Used by analyze route
            data = req.get_json()
            if data:
                text = data.get('text', '')

    if not text:
        logging.warning("No text provided in request")
        return None

    logging.info(f"Analyzing text: {text[:50]}...")  # Log first 50 characters
    return text

def handle_analysis_error(e: Exception, route_name: str) -> Union[Response, Tuple[Response, int]]:
    """
    Handles exceptions during text analysis and returns an appropriate error response.

    Centralizes error handling for different routes (web UI and API).
    Logs the error and returns a user-friendly message.

    Args:
        e: The exception object caught.
        route_name: The name of the route where the error occurred (e.g., 'home', 'analyze').

    Returns:
        A Flask Response object, either a rendered template for 'home' or a JSON response
        for 'analyze'. Includes a status code 500 for server errors.
    """
    logging.error(f"Error in {route_name}: {str(e)}", exc_info=True)
    if route_name == 'home':
        return render_template('index.html', error='An error occurred during analysis')
    elif route_name == 'analyze':
        return jsonify({'error': 'An error occurred during analysis'}), 500
    # Fallback for unexpected route_name, though ideally this shouldn't be reached
    return jsonify({'error': 'An unexpected error occurred'}), 500


@app.route('/', methods=['GET', 'POST'])
def home() -> Union[str, Response, Tuple[Response, int]]:
    """
    Handles GET and POST requests for the main web UI.

    GET: Displays the text input form.
    POST: Receives text from the form, analyzes it using `detect_ai.analyze_text`,
          and displays the perplexity score and whether the text is likely
          AI-generated or human-written. Handles errors using `handle_analysis_error`.

    Returns:
        A rendered HTML template ('index.html') with analysis results or error messages.
        Can also return a Response object in case of errors handled by `handle_analysis_error`.
    """
    logging.info("Home route accessed")
    if request.method == 'POST':
        text = _extract_and_validate_text(request)
        if text is None:
            return render_template('index.html', error='No text provided')
        
        try:
            logging.info("Starting text analysis")
            perplexity = analyze_text(text)
            logging.info(f"Analysis complete. Perplexity: {perplexity}")
            result_text = "Likely AI-generated" if perplexity < app.config['PERPLEXITY_THRESHOLD'] else "Likely human-written"
            return render_template('index.html', result={'text': result_text, 'perplexity': perplexity})
        except Exception as e:
            return handle_analysis_error(e, 'home')
    
    return render_template('index.html')

@app.route('/health', methods=['GET'])
def health_check() -> Tuple[Response, int]:
    """
    Provides a simple health check endpoint.

    Returns:
        A JSON response indicating the service status is "healthy" and HTTP status code 200.
    """
    return jsonify({"status": "healthy"}), 200

@app.route('/analyze', methods=['POST'])
def analyze() -> Tuple[Response, int]:
    """
    Handles POST requests for text analysis via API.

    Expects a JSON payload with a 'text' field. Analyzes the provided text
    using `detect_ai.analyze_text` and returns the perplexity score.
    Handles errors using `handle_analysis_error`.

    Returns:
        A JSON response containing the 'perplexity' score or an error message,
        along with an appropriate HTTP status code (200 for success, 400 for bad
        request if no text is provided, 500 for analysis errors).
    """
    logging.info("Analyze route accessed")
    text = _extract_and_validate_text(request)
    if text is None:
        return jsonify({'error': 'No text provided'}), 400
    
    try:
        logging.info("Starting text analysis")
        perplexity = analyze_text(text)
        logging.info(f"Analysis complete. Perplexity: {perplexity}")
        return jsonify({'perplexity': perplexity})
    except Exception as e:
        return handle_analysis_error(e, 'analyze')

if __name__ == '__main__':
    logging.info("Application starting")
    app.run(debug=True)