# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions
# workflow

name: Build and deploy Python app to Azure Web App - rhellerud

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install NumPy
        run: |
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install numpy==1.21.6 -v
          pip show numpy

      - name: Verify NumPy installation
        run: |
          source venv/bin/activate
          python -c "import numpy; print(numpy.__version__)"

      - name: Install other dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt -v
          pip freeze > installed_requirements.txt
          cat installed_requirements.txt

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Create deployment package
        run: |
          source venv/bin/activate
          zip -r new-python-app.zip . -x "*.git*"

      - name: List contents of current directory
        run: ls -la

      - name: Display zip file info
        run: file new-python-app.zip

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: new-python-app.zip

      - name: Create startup command file
        run: |
          echo "gunicorn --bind=0.0.0.0 --timeout 600 app:app" > startup.txt

      - name: Download GPT-2 model
        run: |
          python -c "from detect_ai import download_model_and_tokenizer; download_model_and_tokenizer()"
        continue-on-error: true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Increase SCM timeout
        run: |
          az webapp config set --resource-group ai-detection --name rhellerud --generic-configurations "{'SCM_COMMAND_IDLE_TIMEOUT':'1800'}"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'rhellerud'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './new-python-app.zip'

      - name: Output deployment results
        if: always()
        run: |
          echo "Deployment Status: ${{ steps.deploy-to-webapp.outcome }}"
          echo "Deployment Output: ${{ steps.deploy-to-webapp.outputs.webapp-url }}"

      - name: Check deployment package contents
        run: unzip -l new-python-app.zip

      - name: View application logs
        run: |
          az webapp log tail --name rhellerud --resource-group ai-detection

      - name: Wait for app to start and perform health check
        run: |
          sleep 120  # Wait for 2 minutes
          curl -sSf https://rhellerud.azurewebsites.net || echo "Health check failed"